//  Fisher-Yates shuffle
function shuffle(array) {
	var i = 0,
		j = 0,
		temp = null;

	for (i = array.length - 1; i > 0; i -= 1) {
		j = Math.floor(Math.random() * (i + 1));
		temp = array[i];
		array[i] = array[j];
		array[j] = temp;
	}

	return array;
}

function getCrawlSeverity(id) {
	var crawl = { "SVS": true, "SVR": true, "TOR": true, "FFW": true, "FFS": true, "HUW": true, "EWW": true }[id]
	if (crawl) return crawl;
	else { return false; }
}

//new icon function
var codeToCurrent = {
	401: { iconFile: 'Ts', textModifier: 'Light Rain with Thunder' },
	429: { iconFile: 'Ts', textModifier: 'Thunderstorm' },
	470: { iconFile: 'Ts', textModifier: 'Thunderstorm / Windy / Fog' },
	471: { iconFile: 'Ts', textModifier: 'Light Rain with Thunder' },
	472: { iconFile: 'Ts', textModifier: 'Heavy Thunderstorm / Fog' },
	480: { iconFile: 'Ts', textModifier: 'Thunderstorm / Fog' },
	481: { iconFile: 'Ts', textModifier: 'Light Rain with Thunder' },
	482: { iconFile: 'Ts', textModifier: 'Heavy Thunderstorm / Fog' },
	490: { iconFile: 'Ts', textModifier: 'Thunderstorm / Windy' },
	491: { iconFile: 'Ts', textModifier: 'Light Rain with Thunder' },
	492: { iconFile: 'Ts', textModifier: 'Heavy Thunderstorm / Windy' },
	500: { iconFile: 'RaSn', textModifier: 'Rain and Snow' },
	570: { iconFile: 'RaSn', textModifier: 'Rain and Snow / Windy / Fog' },
	580: { iconFile: 'RaSn', textModifier: 'Rain and Snow / Fog' },
	590: { iconFile: 'RaSn', textModifier: 'Rain and Snow / Windy' },
	600: { iconFile: 'RaSlt', textModifier: 'Rain and Sleet' },
	610: { iconFile: 'SltFrzRa', textModifier: 'Sleet and Freezing Rain' },
	640: { iconFile: 'SltFrzRa', textModifier: 'Sleet / Freezing Rain / Windy' },
	650: { iconFile: 'RaSlt', textModifier: 'Rain and Sleet / Windy / Fog' },
	660: { iconFile: 'SltFrzRa', textModifier: 'Sleet / Freezing Rain / Fog' },
	670: { iconFile: 'RaSlt', textModifier: 'Rain and Sleet / Fog' },
	680: { iconFile: 'SltFrzRa', textModifier: 'Sleet / Freezing Rain / Windy' },
	690: { iconFile: 'RaSlt', textModifier: 'Rain and Sleet / Windy' },
	700: { iconFile: 'SnSlt', textModifier: 'Snow and Sleet' },
	701: { iconFile: 'LtSnSlt', textModifier: 'Light Snow and Sleet' },
	705: { iconFile: 'SnSlt', textModifier: 'Snow and Sleet / Windy' },
	706: { iconFile: 'LtSnSlt', textModifier: 'Light Snow and Sleet / Windy' },
	710: { iconFile: 'SnFrzRa', textModifier: 'Snow/ Freezing Rain' },
	711: { iconFile: 'LtSnFrzRa', textModifier: 'Light Snow/ Freezing Rain' },
	715: { iconFile: 'SnFrzRa', textModifier: 'Snow/ Freezing Rain/ Windy' },
	716: { iconFile: 'LtSnFrzRa', textModifier: 'Light Snow/ Freezing Rain' },
	720: { iconFile: 'Mix', textModifier: 'Wintry Mix' },
	725: { iconFile: 'Mix', textModifier: 'Wintry Mix/ Windy' },
	730: { iconFile: 'TsMix', textModifier: 'Thunder/ Wintry Mix' },
	735: { iconFile: 'TsMix', textModifier: 'Thunder/ Wintry Mix/ Windy' },
	750: { iconFile: 'SnSlt', textModifier: 'Snow and Sleet/ Fog' },
	751: { iconFile: 'LtSnSlt', textModifier: 'Light Snow and Sleet/ Fog' },
	755: { iconFile: 'SnSlt', textModifier: 'Snow and Sleet/ Windy/ Fog' },
	756: { iconFile: 'LtSnSlt', textModifier: 'Light Snow and Sleet/ Fog' },
	760: { iconFile: 'SnFrzRa', textModifier: 'Snow/ Freezing Rain/ Fog' },
	761: { iconFile: 'LtSnFrzRa', textModifier: 'Light Snow/ Freezing Rain' },
	765: { iconFile: 'SnFrzRa', textModifier: 'Snow/ Freezing Rain/ Windy' },
	766: { iconFile: 'LtSnFrzRa', textModifier: 'Light Snow/ Freezing Rain' },
	770: { iconFile: 'Mix', textModifier: 'Wintry Mix/ Fog' },
	775: { iconFile: 'Mix', textModifier: 'Wintry Mix/ Windy/ Fog' },
	780: { iconFile: 'TsMix', textModifier: 'Thunder/ Wintry Mix/ Fog' },
	785: { iconFile: 'TsMix', textModifier: 'Thunder/ Wintry Mix/ Windy' },
	800: { iconFile: 'FrzDrz', textModifier: 'Freezing Drizzle' },
	801: { iconFile: 'FrzDrz', textModifier: 'Light Freezing Drizzle' },
	802: { iconFile: 'FrzDrz', textModifier: 'Heavy Freezing Drizzle' },
	810: { iconFile: 'FrzDrz', textModifier: 'Drizzle/ Freezing Drizzle' },
	815: { iconFile: 'FrzDrz', textModifier: 'Drizzle/ Freezing Drizzle' },
	820: { iconFile: 'FrzDrz', textModifier: 'Drizzle/ Freezing Drizzle' },
	825: { iconFile: 'FrzDrz', textModifier: 'Drizzle/ Freezing Drizzle' },
	870: { iconFile: 'FrzDrz', textModifier: 'Freezing Drizzle/ Fog' },
	871: { iconFile: 'FrzDrz', textModifier: 'Light Freezing Drizzle/ Fog' },
	872: { iconFile: 'FrzDrz', textModifier: 'Heavy Freezing Drizzle/ Fog' },
	880: { iconFile: 'FrzDrz', textModifier: 'Freezing Drizzle/ Windy/ Fog' },
	881: { iconFile: 'FrzDrz', textModifier: 'Light Freezing Drizzle/ Fog' },
	882: { iconFile: 'FrzDrz', textModifier: 'Heavy Freezing Drizzle/ Fog' },
	890: { iconFile: 'FrzDrz', textModifier: 'Freezing Drizzle/ Windy' },
	891: { iconFile: 'FrzDrz', textModifier: 'Light Freezing Drizzle' },
	892: { iconFile: 'FrzDrz', textModifier: 'Heavy Freezing Drizzle' },
	900: { iconFile: 'Drz', textModifier: 'Drizzle' },
	901: { iconFile: 'Drz', textModifier: 'Light Drizzle' },
	902: { iconFile: 'Drz', textModifier: 'Heavy Drizzle' },
	910: { iconFile: 'DrzFog', textModifier: 'Drizzle and Fog' },
	980: { iconFile: 'DrzFog', textModifier: 'Drizzle and Fog/ Windy' },
	990: { iconFile: 'Drz', textModifier: 'Drizzle/Windy' },
	991: { iconFile: 'Drz', textModifier: 'Light Drizzle/ Windy' },
	992: { iconFile: 'Drz', textModifier: 'Heavy Drizzle/ Windy' },
	1000: { iconFile: 'FrzRa', textModifier: 'Freezing Rain' },
	1001: { iconFile: 'FrzRa', textModifier: 'Light Freezing Rain' },
	1002: { iconFile: 'FrzRa', textModifier: 'Heavy Freezing Rain' },
	1010: { iconFile: 'RaFrzRa', textModifier: 'Rain/ Freezing Rain' },
	1040: { iconFile: 'RaFrzRa', textModifier: 'Rain/ Freezing Rain/ Windy' },
	1050: { iconFile: 'RaFrzRa', textModifier: 'Rain/ Freezing Rain/ Windy' },
	1060: { iconFile: 'RaFrzRa', textModifier: 'Rain/ Freezing Rain/ Fog' },
	1070: { iconFile: 'FrzRa', textModifier: 'Freezing Rain/ Fog' },
	1071: { iconFile: 'FrzRa', textModifier: 'Light Freezing Rain/ Fog' },
	1072: { iconFile: 'FrzRa', textModifier: 'Heavy Freezing Rain/ Fog' },
	1080: { iconFile: 'FrzRa', textModifier: 'Freezing Rain/ Windy/ Fog' },
	1081: { iconFile: 'FrzRa', textModifier: 'Light Freezing Rain/ Fog' },
	1082: { iconFile: 'FrzRa', textModifier: 'Heavy Freezing Rain/ Fog' },
	1090: { iconFile: 'FrzRa', textModifier: 'Freezing Rain/ Windy' },
	1091: { iconFile: 'FrzRa', textModifier: 'Light Freezing Rain/ Windy' },
	1092: { iconFile: 'FrzRa', textModifier: 'Heavy Freezing Rain/ Windy' },
	1100: { iconFile: 'LtRa', textModifier: 'Rain Shower' },
	1101: { iconFile: 'LtRa', textModifier: 'Light Rain Shower' },
	1102: { iconFile: 'Ra', textModifier: 'Heavy Rain Shower' },
	1170: { iconFile: 'LtRa', textModifier: 'Rain Shower/ Windy/ Fog' },
	1171: { iconFile: 'LtRa', textModifier: 'Light Rain Shower/ Windy' },
	1172: { iconFile: 'WndRa', textModifier: 'Heavy Rain Shower/ Windy' },
	1180: { iconFile: 'LtRa', textModifier: 'Rain Shower/ Fog' },
	1181: { iconFile: 'LtRa', textModifier: 'Light Rain Shower/ Fog' },
	1182: { iconFile: 'Ra', textModifier: 'Heavy Rain Shower/ Fog' },
	1190: { iconFile: 'LtRa', textModifier: 'Rain Shower/ Windy' },
	1191: { iconFile: 'LtRa', textModifier: 'Light Rain Shower/ Windy' },
	1192: { iconFile: 'WndRa', textModifier: 'Heavy Rain Shower/ Windy' },
	1200: { iconFile: 'Ra', textModifier: 'Rain' },
	1201: { iconFile: 'LtRa', textModifier: 'Light Rain' },
	1202: { iconFile: 'HvyRa', textModifier: 'Heavy Rain' },
	1210: { iconFile: 'SltFrzRa', textModifier: 'Freezing Rain/ Sleet' },
	1211: { iconFile: 'SltFrzRa', textModifier: 'Light Freezing Rain/ Sleet' },
	1212: { iconFile: 'SltFrzRa', textModifier: 'Heavy Freezing Rain/ Sleet' },
	1215: { iconFile: 'SltFrzRa', textModifier: 'Freezing Rain/ Sleet/ Fog' },
	1216: { iconFile: 'SltFrzRa', textModifier: 'Light Freezing Rain/ Sleet' },
	1217: { iconFile: 'SltFrzRa', textModifier: 'Heavy Freezing Rain/ Sleet' },
	1220: { iconFile: 'SltFrzRa', textModifier: 'Freezing Rain/ Sleet/ Windy' },
	1221: { iconFile: 'SltFrzRa', textModifier: 'Light Freezing Rain/ Sleet' },
	1222: { iconFile: 'SltFrzRa', textModifier: 'Heavy Freezing Rain/ Sleet' },
	1225: { iconFile: 'SltFrzRa', textModifier: 'Freezing Rain/ Sleet/ Windy' },
	1226: { iconFile: 'SltFrzRa', textModifier: 'Light Freezing Rain/ Sleet' },
	1227: { iconFile: 'SltFrzRa', textModifier: 'Heavy Freezing Rain/ Sleet' },
	1230: { iconFile: 'RaFrzRa', textModifier: 'Rain/ Freezing Rain' },
	1231: { iconFile: 'RaFrzRa', textModifier: 'Light Rain/ Freezing Rain' },
	1232: { iconFile: 'RaFrzRa', textModifier: 'Heavy Rain/ Freezing Rain' },
	1235: { iconFile: 'RaFrzRa', textModifier: 'Rain/ Freezing Rain/ Fog' },
	1236: { iconFile: 'RaFrzRa', textModifier: 'Light Rain/ Freezing Rain' },
	1237: { iconFile: 'RaFrzRa', textModifier: 'Heavy Rain/ Freezing Rain' },
	1240: { iconFile: 'RaFrzRa', textModifier: 'Rain/ Freezing Rain/ Windy' },
	1241: { iconFile: 'RaFrzRa', textModifier: 'Light Rain/ Freezing Rain' },
	1242: { iconFile: 'RaFrzRa', textModifier: 'Heavy Rain/ Freezing Rain' },
	1245: { iconFile: 'RaFrzRa', textModifier: 'Rain/ Freezing Rain/ Windy' },
	1246: { iconFile: 'RaFrzRa', textModifier: 'Light Rain/ Freezing Rain' },
	1247: { iconFile: 'RaFrzRa', textModifier: 'Heavy Rain/ Freezing Rain' },
	1270: { iconFile: 'WndRa', textModifier: 'Rain/Windy/Fog' },
	1271: { iconFile: 'LtRa', textModifier: 'Light Rain/ Windy/ Fog' },
	1272: { iconFile: 'WndRa', textModifier: 'Heavy Rain/ Windy/ Fog' },
	1280: { iconFile: 'Ra', textModifier: 'Rain/Fog' },
	1281: { iconFile: 'LtRa', textModifier: 'Light Rain/Fog' },
	1282: { iconFile: 'HvyRa', textModifier: 'Heavy Rain/Fog' },
	1290: { iconFile: 'WndRa', textModifier: 'Rain/Windy' },
	1291: { iconFile: 'LtRa', textModifier: 'Light Rain/Windy' },
	1292: { iconFile: 'WndRa', textModifier: 'Heavy Rain/ Windy' },
	1310: { iconFile: 'SnFl', textModifier: 'Snow Grains' },
	1311: { iconFile: 'SnFl', textModifier: 'Light Snow Grains' },
	1312: { iconFile: 'LtSn', textModifier: 'Heavy Snow Grains' },
	1370: { iconFile: 'SnFl', textModifier: 'Snow Grains/ Windy/ Fog' },
	1371: { iconFile: 'SnFl', textModifier: 'Light Snow Grains/ Windy' },
	1372: { iconFile: 'LtSn', textModifier: 'Heavy Snow Grains/ Windy' },
	1380: { iconFile: 'SnFl', textModifier: 'Snow Grains/Fog' },
	1381: { iconFile: 'SnFl', textModifier: 'Light Snow Grains/ Fog' },
	1382: { iconFile: 'LtSn', textModifier: 'Heavy Snow Grains/ Fog' },
	1390: { iconFile: 'SnFl', textModifier: 'Snow Grains/ Windy' },
	1391: { iconFile: 'SnFl', textModifier: 'Light Snow Grains/ Windy' },
	1392: { iconFile: 'LtSn', textModifier: 'Heavy Snow Grains/ Windy' },
	1400: { iconFile: 'LtSn', textModifier: 'Snow Shower' },
	1401: { iconFile: 'SnFl', textModifier: 'Light Snow Shower' },
	1402: { iconFile: 'Sn', textModifier: 'Heavy Snow Shower' },
	1470: { iconFile: 'LtSn', textModifier: 'Snow Shower/ Windy/ Fog' },
	1471: { iconFile: 'SnFl', textModifier: 'Light Snow Shower/ Windy' },
	1472: { iconFile: 'WndSn', textModifier: 'Heavy Snow Shower/ Windy' },
	1480: { iconFile: 'LtSn', textModifier: 'Snow Shower/ Fog' },
	1481: { iconFile: 'SnFl', textModifier: 'Light Snow Shower/ Fog' },
	1482: { iconFile: 'Sn', textModifier: 'Heavy Snow Shower/ Fog' },
	1490: { iconFile: 'LtSn', textModifier: 'Snow Shower/ Windy' },
	1491: { iconFile: 'SnFl', textModifier: 'Light Snow Shower/ Windy' },
	1492: { iconFile: 'WndSn', textModifier: 'Heavy Snow Shower/ Windy' },
	1500: { iconFile: 'BlowSn', textModifier: 'Blowing Snow' },
	1501: { iconFile: 'BlowSn', textModifier: 'Drifting Snow' },
	1509: { iconFile: 'BlowSn', textModifier: 'Blowing Snow Nearby' },
	1570: { iconFile: 'BlowSn', textModifier: 'Blowing Snow/ Windy/ Fog' },
	1571: { iconFile: 'BlowSn', textModifier: 'Drifting Snow/ Windy/ Fog' },
	1579: { iconFile: 'BlowSn', textModifier: 'Blowing Snow Nearby/ Windy' },
	1580: { iconFile: 'BlowSn', textModifier: 'Blowing Snow/ Fog' },
	1581: { iconFile: 'BlowSn', textModifier: 'Drifting Snow/ Fog' },
	1589: { iconFile: 'BlowSn', textModifier: 'Blowing Snow Nearby/ Fog' },
	1590: { iconFile: 'BlowSn', textModifier: 'Blowing Snow/ Windy' },
	1591: { iconFile: 'BlowSn', textModifier: 'Drifting Snow/ Windy' },
	1599: { iconFile: 'BlowSn', textModifier: 'Blowing Snow Nearby/ Windy' },
	1600: { iconFile: 'Sn', textModifier: 'Snow' },
	1601: { iconFile: 'LtSn', textModifier: 'Light Snow' },
	1602: { iconFile: 'HvySn', textModifier: 'Heavy Snow' },
	1630: { iconFile: 'TsSn', textModifier: 'Snow and Thunder/ Windy/ Fog' },
	1631: { iconFile: 'TsSn', textModifier: 'Light Snow with Thunder' },
	1632: { iconFile: 'TsSn', textModifier: 'Heavy Snow with Thunder' },
	1640: { iconFile: 'TsSn', textModifier: 'Snow and Thunder' },
	1641: { iconFile: 'TsSn', textModifier: 'Light Snow with Thunder' },
	1642: { iconFile: 'TsSn', textModifier: 'Heavy Snow with Thunder' },
	1650: { iconFile: 'TsSn', textModifier: 'Snow and Thunder/ Windy' },
	1651: { iconFile: 'TsSn', textModifier: 'Light Snow with Thunder' },
	1652: { iconFile: 'TsSn', textModifier: 'Heavy Snow with Thunder' },
	1660: { iconFile: 'TsSn', textModifier: 'Snow and Thunder/ Fog' },
	1661: { iconFile: 'TsSn', textModifier: 'Light Snow with Thunder' },
	1662: { iconFile: 'TsSn', textModifier: 'Heavy Snow with Thunder' },
	1670: { iconFile: 'Sn', textModifier: 'Snow/Fog' },
	1671: { iconFile: 'LtSn', textModifier: 'Light Snow/Fog' },
	1672: { iconFile: 'HvySn', textModifier: 'Heavy Snow/Fog' },
	1680: { iconFile: 'WndSn', textModifier: 'Snow/Windy/Fog' },
	1681: { iconFile: 'LtSn', textModifier: 'Light Snow/ Windy/ Fog' },
	1682: { iconFile: 'WndSn', textModifier: 'Heavy Snow/ Windy/ Fog' },
	1690: { iconFile: 'WndSn', textModifier: 'Snow/Windy' },
	1691: { iconFile: 'LtSn', textModifier: 'Light Snow/ Windy' },
	1692: { iconFile: 'WndSn', textModifier: 'Heavy Snow/ Windy' },
	1700: { iconFile: 'Ts', textModifier: 'Hail' },
	1701: { iconFile: 'Ts', textModifier: 'Small Hail' },
	1730: { iconFile: 'Ts', textModifier: 'Thunder and Hail/ Windy' },
	1731: { iconFile: 'Ts', textModifier: 'Thunder and Small Hail' },
	1740: { iconFile: 'Ts', textModifier: 'Thunder and Hail' },
	1741: { iconFile: 'Ts', textModifier: 'Thunder and Small Hail' },
	1750: { iconFile: 'Ts', textModifier: 'Thunder and Hail/ Windy/ Fog' },
	1751: { iconFile: 'Ts', textModifier: 'Thunder and Small Hail/ Fog' },
	1760: { iconFile: 'Ts', textModifier: 'Thunder and Hail/ Fog' },
	1761: { iconFile: 'Ts', textModifier: 'Thunder and Small Hail/ Fog' },
	1770: { iconFile: 'Ts', textModifier: 'Hail/Fog' },
	1771: { iconFile: 'Ts', textModifier: 'Small Hail/Fog' },
	1780: { iconFile: 'Ts', textModifier: 'Hail/Windy/Fog' },
	1781: { iconFile: 'Ts', textModifier: 'Small Hail/ Windy/ Fog' },
	1790: { iconFile: 'Ts', textModifier: 'Hail/Windy' },
	1791: { iconFile: 'Ts', textModifier: 'Small Hail/Windy' },
	1800: { iconFile: 'Slt', textModifier: 'Sleet' },
	1801: { iconFile: 'Slt', textModifier: 'Light Sleet' },
	1802: { iconFile: 'Slt', textModifier: 'Heavy Sleet' },
	1810: { iconFile: 'Slt', textModifier: 'Snow Pellets' },
	1811: { iconFile: 'TsSlt', textModifier: 'Thunder and Snow Pellets' },
	1816: { iconFile: 'TsSlt', textModifier: 'Thunder and Snow Pellets' },
	1821: { iconFile: 'TsSlt', textModifier: 'Thunder and Snow Pellets' },
	1826: { iconFile: 'TsSlt', textModifier: 'Thunder and Snow Pellets' },
	1830: { iconFile: 'TsSlt', textModifier: 'Sleet and Thunder/ Fog' },
	1831: { iconFile: 'TsSlt', textModifier: 'Light Sleet and Thunder' },
	1832: { iconFile: 'TsSlt', textModifier: 'Heavy Sleet and Thunder' },
	1840: { iconFile: 'TsSlt', textModifier: 'Sleet and Thunder' },
	1841: { iconFile: 'TsSlt', textModifier: 'Light Sleet and Thunder' },
	1842: { iconFile: 'TsSlt', textModifier: 'Heavy Sleet and Thunder' },
	1850: { iconFile: 'Slt', textModifier: 'Sleet/Fog' },
	1851: { iconFile: 'Slt', textModifier: 'Light Sleet/Fog' },
	1852: { iconFile: 'Slt', textModifier: 'Heavy Sleet/Fog' },
	1860: { iconFile: 'Slt', textModifier: 'Snow Pellets/ Fog' },
	1861: { iconFile: 'Slt', textModifier: 'Snow Pellets/ Windy/ Fog' },
	1870: { iconFile: 'Slt', textModifier: 'Snow Pellets/ Windy' },
	1880: { iconFile: 'TsSlt', textModifier: 'Sleet and Thunder/ Windy' },
	1881: { iconFile: 'TsSlt', textModifier: 'Light Sleet and Thunder' },
	1882: { iconFile: 'TsSlt', textModifier: 'Heavy Sleet and Thunder' },
	1885: { iconFile: 'TsSlt', textModifier: 'Sleet and Thunder/ Windy' },
	1886: { iconFile: 'TsSlt', textModifier: 'Light Sleet and Thunder' },
	1887: { iconFile: 'TsSlt', textModifier: 'Heavy Sleet and Thunder' },
	1890: { iconFile: 'Slt', textModifier: 'Sleet/Windy' },
	1891: { iconFile: 'Slt', textModifier: 'Light Sleet/Windy' },
	1892: { iconFile: 'Slt', textModifier: 'Heavy Sleet/ Windy' },
	1895: { iconFile: 'Slt', textModifier: 'Sleet/Windy/Fog' },
	1896: { iconFile: 'Slt', textModifier: 'Light Sleet/ Windy/ Fog' },
	1897: { iconFile: 'Slt', textModifier: 'Heavy Sleet/ Windy/ Fog' },
	1900: { iconFile: 'Dust', textModifier: 'Widespread Dust' },
	1901: { iconFile: 'Dust', textModifier: 'Low Drifting Dust' },
	1902: { iconFile: 'Dust', textModifier: 'Blowing Dust' },
	1910: { iconFile: 'Dust', textModifier: 'Sand' },
	1911: { iconFile: 'Dust', textModifier: 'Low Drifting Sand' },
	1912: { iconFile: 'Dust', textModifier: 'Blowing Sand' },
	1919: { iconFile: 'Dust', textModifier: 'Blowing Sand Nearby' },
	1920: { iconFile: 'Dust', textModifier: 'Sandstorm' },
	1922: { iconFile: 'Dust', textModifier: 'Heavy Sandstorm' },
	1929: { iconFile: 'Dust', textModifier: 'Sandstorm in the Vicinity' },
	1930: { iconFile: 'Dust', textModifier: 'Volcanic Ash' },
	1931: { iconFile: 'Dust', textModifier: 'Duststorm' },
	1932: { iconFile: 'Dust', textModifier: 'Heavy Duststorm' },
	1939: { iconFile: 'Dust', textModifier: 'Duststorm in the Vicinity' },
	1960: { iconFile: 'Dust', textModifier: 'Volcanic Ash/ Windy' },
	1961: { iconFile: 'Dust', textModifier: 'Duststorm/Windy' },
	1962: { iconFile: 'Dust', textModifier: 'Heavy Duststorm/ Windy' },
	1969: { iconFile: 'Wnd', textModifier: 'Duststorm in the Vicinity' },
	1970: { iconFile: 'Dust', textModifier: 'Sandstorm/Windy' },
	1972: { iconFile: 'Dust', textModifier: 'Heavy Sandstorm/ Windy' },
	1979: { iconFile: 'Wnd', textModifier: 'Sandstorm in the Vicinity' },
	1980: { iconFile: 'Dust', textModifier: 'Sand/Windy' },
	1981: { iconFile: 'Dust', textModifier: 'Low Drifting Sand/ Windy' },
	1982: { iconFile: 'Dust', textModifier: 'Blowing Sand/ Windy' },
	1989: { iconFile: 'Wnd', textModifier: 'Blowing Sand Nearby/ Windy' },
	1990: { iconFile: 'Dust', textModifier: 'Widespread Dust/ Windy' },
	1991: { iconFile: 'Dust', textModifier: 'Low Drifting Dust/ Windy' },
	1992: { iconFile: 'Dust', textModifier: 'Blowing Dust/ Windy' },
	2000: { iconFile: 'Fog', textModifier: 'Fog' },
	2001: { iconFile: 'Fog', textModifier: 'Patches of Fog' },
	2002: { iconFile: 'Cld', textModifier: 'Mist' },
	2021: { iconFile: 'Fog', textModifier: 'Shallow Fog' },
	2022: { iconFile: 'Fog', textModifier: 'Partial Fog' },
	2081: { iconFile: 'Fog', textModifier: 'Shallow Fog/ Windy' },
	2082: { iconFile: 'Fog', textModifier: 'Partial Fog/ Windy' },
	2090: { iconFile: 'Fog', textModifier: 'Fog/Windy' },
	2091: { iconFile: 'Fog', textModifier: 'Patches of Fog/ Windy' },
	2092: { iconFile: 'Wnd', textModifier: 'Mist/Windy' },
	2100: { iconFile: 'Haze', textModifier: 'Haze' },
	2190: { iconFile: 'Haze', textModifier: 'Haze/Windy' },
	2200: { iconFile: 'Smoke', textModifier: 'Smoke' },
	2290: { iconFile: 'Smoke', textModifier: 'Smoke/Windy' },
	2410: { iconFile: 'Wnd', textModifier: 'Blowing Spray' },
	2420: { iconFile: 'Wnd', textModifier: 'Sand/Dust Whirlwinds' },
	2429: { iconFile: 'Wnd', textModifier: 'Sand/Dust Whirls Nearby' },
	2430: { iconFile: 'Wnd', textModifier: 'Squalls' },
	2450: { iconFile: 'Wnd', textModifier: 'Squalls/ Windy/ Fog' },
	2460: { iconFile: 'Wnd', textModifier: 'Squalls/Fog' },
	2470: { iconFile: 'Wnd', textModifier: 'Squalls/Windy' },
	2480: { iconFile: 'Wnd', textModifier: 'Sand/ Dust Whirlwinds/ Windy' },
	2489: { iconFile: 'Wnd', textModifier: 'Sand/Dust Whirls Nearby' },
	2490: { iconFile: 'Wnd', textModifier: 'Blowing Spray/ Windy' },
	2510: { iconFile: 'Frigid', textModifier: 'Ice Crystals' },
	2570: { iconFile: 'Frigid', textModifier: 'Ice Crystals/ Windy/ Fog' },
	2580: { iconFile: 'Frigid', textModifier: 'Ice Crystals/Fog' },
	2590: { iconFile: 'Frigid', textModifier: 'Ice Crystals/ Windy' },
	2600: { iconFile: 'Cld', textModifier: 'Cloudy' },
	2680: { iconFile: 'Cld', textModifier: 'Showers in the Vicinity' },
	2681: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	2685: { iconFile: 'CldWnd', textModifier: 'Showers in the Vicinity' },
	2686: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	2690: { iconFile: 'CldWnd', textModifier: 'Cloudy/Windy' },
	2700: { iconFile: 'NMc', textModifier: 'Mostly Cloudy' },
	2780: { iconFile: 'NMc', textModifier: 'Showers in the Vicinity' },
	2781: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	2785: { iconFile: 'CldWnd', textModifier: 'Showers in the Vicinity' },
	2786: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	2790: { iconFile: 'CldWnd', textModifier: 'Mostly Cloudy/ Windy' },
	2800: { iconFile: 'DMc', textModifier: 'Mostly Cloudy' },
	2880: { iconFile: 'DMc', textModifier: 'Showers in the Vicinity' },
	2881: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	2885: { iconFile: 'CldWnd', textModifier: 'Showers in the Vicinity' },
	2886: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	2890: { iconFile: 'CldWnd', textModifier: 'Mostly Cloudy/ Windy' },
	2900: { iconFile: 'NPc', textModifier: 'Partly Cloudy' },
	2980: { iconFile: 'NPc', textModifier: 'Showers in the Vicinity' },
	2981: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	2985: { iconFile: 'NPcWnd', textModifier: 'Showers in the Vicinity' },
	2986: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	2990: { iconFile: 'NPcWnd', textModifier: 'Partly Cloudy/ Windy' },
	3000: { iconFile: 'DPc', textModifier: 'Partly Cloudy' },
	3080: { iconFile: 'DPc', textModifier: 'Showers in the Vicinity' },
	3081: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	3085: { iconFile: 'PcWnd', textModifier: 'Showers in the Vicinity' },
	3086: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	3090: { iconFile: 'PcWnd', textModifier: 'Partly Cloudy/ Windy' },
	3100: { iconFile: 'NClr', textModifier: 'Clear' },
	3180: { iconFile: 'NClr', textModifier: 'Showers in the Vicinity' },
	3181: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	3185: { iconFile: 'NClrWnd', textModifier: 'Showers in the Vicinity' },
	3186: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	3190: { iconFile: 'NClrWnd', textModifier: 'Clear/Windy' },
	3200: { iconFile: 'Sun', textModifier: 'Sunny' },
	3280: { iconFile: 'Sun', textModifier: 'Showers in the Vicinity' },
	3281: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	3285: { iconFile: 'SunWnd', textModifier: 'Showers in the Vicinity' },
	3286: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	3290: { iconFile: 'SunWnd', textModifier: 'Sunny/Windy' },
	3300: { iconFile: 'NClrB12', textModifier: 'Fair' },
	3380: { iconFile: 'NClrB12', textModifier: 'Showers in the Vicinity' },
	3381: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	3385: { iconFile: 'NPcWnd', textModifier: 'Showers in the Vicinity' },
	3386: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	3390: { iconFile: 'NClrWnd', textModifier: 'Fair/Windy' },
	3400: { iconFile: 'DClrB12', textModifier: 'Fair' },
	3480: { iconFile: 'DClrB12', textModifier: 'Showers in the Vicinity' },
	3481: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	3485: { iconFile: 'PcWnd', textModifier: 'Showers in the Vicinity' },
	3486: { iconFile: 'Fog', textModifier: 'Showers in the Vicinity' },
	3490: { iconFile: 'SunWnd', textModifier: 'Fair/Windy' },
	3540: { iconFile: 'Thun', textModifier: 'Thunder' },
	3549: { iconFile: 'Thun', textModifier: 'Thunder in the Vicinity' },
	3570: { iconFile: 'Thun', textModifier: 'Thunder/ Windy/ Fog' },
	3579: { iconFile: 'Thun', textModifier: 'Thunder in the Vicinity' },
	3580: { iconFile: 'Thun', textModifier: 'Thunder/Fog' },
	3589: { iconFile: 'Thun', textModifier: 'Thunder in the Vicinity' },
	3590: { iconFile: 'Thun', textModifier: 'Thunder/Windy' },
	3599: { iconFile: 'Thun', textModifier: 'Thunder in the Vicinity' },
	3840: { iconFile: 'Thun', textModifier: 'Thunder' },
	3849: { iconFile: 'Thun', textModifier: 'Thunder in the Vicinity' },
	3870: { iconFile: 'Thun', textModifier: 'Thunder/ Windy/ Fog' },
	3879: { iconFile: 'Thun', textModifier: 'Thunder in the Vicinity' },
	3880: { iconFile: 'Thun', textModifier: 'Thunder/Fog' },
	3889: { iconFile: 'Thun', textModifier: 'Thunder in the Vicinity' },
	3890: { iconFile: 'Thun', textModifier: 'Thunder/Windy' },
	3899: { iconFile: 'Thun', textModifier: 'Thunder in the Vicinity' },
	4400: { iconFile: 'Cld', textModifier: 'Unknown Precipitation' },
	4470: { iconFile: 'Fog', textModifier: 'Unknown Precipitation/ Fog' },
	4480: { iconFile: 'Wnd', textModifier: 'Unknown Precipitation' },
	4490: { iconFile: 'Fog', textModifier: 'Unknown Precipitation/ Fog' },
}
var codetoFcst = {
	300: { iconFile: 'StrTs', textModifier: "Strong T'storms" },
	310: { iconFile: 'StrTs', textModifier: "Strong T'storms / Wind" },
	400: { iconFile: 'Tss', textModifier: "T'storms" },
	402: { iconFile: 'Tss', textModifier: "Heavy T'storms" },
	410: { iconFile: 'Tss', textModifier: "T'storms / Wind" },
	412: { iconFile: 'Tss', textModifier: "Heavy T'storms / Wind" },
	500: { iconFile: 'RaSn', textModifier: 'Rain / Snow' },
	510: { iconFile: 'RaSn', textModifier: 'Rain / Snow / Wind' },
	600: { iconFile: 'RaSlt', textModifier: 'Rain / Sleet' },
	601: { iconFile: 'RaSlt', textModifier: 'Light Rain / Sleet' },
	610: { iconFile: 'RaSlt', textModifier: 'Rain / Sleet / Wind' },
	611: { iconFile: 'RaSlt', textModifier: 'Light Rain / Sleet / Wind' },
	700: { iconFile: 'Mix', textModifier: 'Wintry Mix' },
	701: { iconFile: 'LtMix', textModifier: 'Light Wintry Mix' },
	710: { iconFile: 'Mix', textModifier: 'Wintry Mix / Wind' },
	711: { iconFile: 'LtMix', textModifier: 'Light Wintry Mix / Wind' },
	800: { iconFile: 'FrzDrz', textModifier: 'Freezing Drizzle' },
	810: { iconFile: 'FrzDrz', textModifier: 'Freezing Drizzle / Wind' },
	850: { iconFile: 'FrzDrz', textModifier: 'Freezing Drizzle / Fog' },
	900: { iconFile: 'Drz', textModifier: 'Drizzle' },
	910: { iconFile: 'Drz', textModifier: 'Drizzle / Wind' },
	950: { iconFile: 'DrzFog', textModifier: 'Drizzle / Fog' },
	1000: { iconFile: 'FrzRa', textModifier: 'Freezing Rain' },
	1001: { iconFile: 'FrzRa', textModifier: 'Light Freezing Rain' },
	1002: { iconFile: 'FrzRa', textModifier: 'Heavy Freezing Rain' },
	1010: { iconFile: 'FrzRa', textModifier: 'Freezing Rain / Wind' },
	1011: { iconFile: 'FrzRa', textModifier: 'Light Freezing Rain / Wind' },
	1012: { iconFile: 'FrzRa', textModifier: 'Heavy Freezing Rain / Wind' },
	1051: { iconFile: 'FrzDrz', textModifier: 'Light Freezing Rain / Fog' },
	1100: { iconFile: 'LtRa', textModifier: 'Showers' },
	1110: { iconFile: 'LtRa', textModifier: 'Showers / Wind' },
	1140: { iconFile: 'LtRa', textModifier: "T'showers" },
	1170: { iconFile: 'LtRa', textModifier: "T'showers / Wind" },
	1200: { iconFile: 'Ra', textModifier: 'Rain' },
	1201: { iconFile: 'LtRa', textModifier: 'Light Rain' },
	1210: { iconFile: 'WndRa', textModifier: 'Rain / Wind' },
	1211: { iconFile: 'WndRa', textModifier: 'Light Rain / Wind' },
	1240: { iconFile: 'Ra', textModifier: 'Rain / Thunder' },
	1251: { iconFile: 'LtRa', textModifier: 'Light Rain / Fog' },
	1270: { iconFile: 'WndRa', textModifier: 'Rain / Thunder / Wind' },
	1300: { iconFile: 'SnFl', textModifier: 'Flurries' },
	1310: { iconFile: 'SnFl', textModifier: 'Flurries / Wind' },
	1400: { iconFile: 'LtSn', textModifier: 'Snow Shower' },
	1410: { iconFile: 'LtSn', textModifier: 'Snow Shower / Wind' },
	1600: { iconFile: 'Sn', textModifier: 'Snow' },
	1601: { iconFile: 'LtSn', textModifier: 'Light Snow' },
	1610: { iconFile: 'WndSn', textModifier: 'Snow / Wind' },
	1611: { iconFile: 'WndSn', textModifier: 'Light Snow / Wind' },
	1651: { iconFile: 'LtSn', textModifier: 'Light Snow / Fog' },
	1800: { iconFile: 'Slt', textModifier: 'Sleet' },
	1801: { iconFile: 'Slt', textModifier: 'Light Sleet' },
	1810: { iconFile: 'Slt', textModifier: 'Sleet / Wind' },
	1811: { iconFile: 'Slt', textModifier: 'Light Sleet / Wind' },
	2000: { iconFile: 'Fog', textModifier: 'Foggy' },
	2010: { iconFile: 'Fog', textModifier: 'Foggy / Wind' },
	2100: { iconFile: 'Haze', textModifier: 'Hazy' },
	2110: { iconFile: 'Wnd', textModifier: 'Hazy / Wind' },
	2600: { iconFile: 'Cld', textModifier: 'Cloudy' },
	2610: { iconFile: 'CldWnd', textModifier: 'Cloudy / Wind' },
	2700: { iconFile: 'NMc', textModifier: 'Mostly Cloudy' },
	2710: { iconFile: 'Wnd', textModifier: 'Mostly Cloudy / Wind' },
	2800: { iconFile: 'DMc', textModifier: 'Mostly Cloudy' },
	2810: { iconFile: 'Wnd', textModifier: 'Mostly Cloudy / Wind' },
	2900: { iconFile: 'NPc', textModifier: 'Partly Cloudy' },
	2910: { iconFile: 'NPcWnd', textModifier: 'Partly Cloudy / Wind' },
	3000: { iconFile: 'DPc', textModifier: 'Partly Cloudy' },
	3010: { iconFile: 'PcWnd', textModifier: 'Partly Cloudy / Wind' },
	3100: { iconFile: 'NClr', textModifier: 'Clear' },
	3110: { iconFile: 'NClrWnd', textModifier: 'Clear / Wind' },
	3200: { iconFile: 'Sun', textModifier: 'Sunny' },
	3210: { iconFile: 'SunWnd', textModifier: 'Sunny / Wind' },
	3300: { iconFile: 'NClr', textModifier: 'Mostly Clear' },
	3310: { iconFile: 'Wnd', textModifier: 'Mostly Clear / Wind' },
	3400: { iconFile: 'MSun', textModifier: 'Mostly Sunny' },
	3410: { iconFile: 'SunWnd', textModifier: 'Mostly Sunny / Wind' },
	3700: { iconFile: 'IsoTs', textModifier: "Isolated T'storms" },
	3709: { iconFile: 'NSctTs', textModifier: "Isolated T'storms" },
	3710: { iconFile: 'IsoTs', textModifier: "Isolated T'storms / Wind" },
	3719: { iconFile: 'NSctTs', textModifier: "Isolated T'storms / Wind" },
	3800: { iconFile: 'SctTs', textModifier: "Sct'd T'storms" },
	3809: { iconFile: 'NSctTs', textModifier: "Sct'd T'storms" },
	3810: { iconFile: 'SctTs', textModifier: "Sct'd T'storms / Wind" },
	3819: { iconFile: 'NSctTs', textModifier: "Sct'd T'storms / Wind" },
	3900: { iconFile: 'SctSh', textModifier: "Sct'd Showers" },
	3909: { iconFile: 'NSctSh', textModifier: "Sct'd Showers" },
	3910: { iconFile: 'SctSh', textModifier: "Sct'd Showers / Wind" },
	3919: { iconFile: 'NSctSh', textModifier: "Sct'd Showers / Wind" },
	4000: { iconFile: 'HvyRa', textModifier: 'Heavy Rain' },
	4010: { iconFile: 'WndRa', textModifier: 'Heavy Rain / Wind' },
	4100: { iconFile: 'SctSnSh', textModifier: "Sct'd Snow Showers" },
	4109: { iconFile: 'NSctSnSh', textModifier: "Sct'd Snow Showers" },
	4110: { iconFile: 'SctSnSh', textModifier: "Sct'd Snow Shower / Wind" },
	4119: { iconFile: 'NSctSnSh', textModifier: "Sct'd Snow Showers / Wind" },
	4200: { iconFile: 'HvySn', textModifier: 'Heavy Snow' },
	4210: { iconFile: 'WndSn', textModifier: 'Heavy Snow / Wind' },
	4300: { iconFile: 'Blizz', textModifier: 'Blizzard' },
	4500: { iconFile: 'Drz', textModifier: 'Sprinkles' },
	4510: { iconFile: 'Drz', textModifier: 'Sprinkles / Wind' },
	4600: { iconFile: 'FewShw', textModifier: 'Few Showers' },
	4610: { iconFile: 'FewShw', textModifier: 'Few Showers / Wind' },
	4700: { iconFile: 'LtSn', textModifier: 'Few Snow Showers' },
	4710: { iconFile: 'LtSn', textModifier: 'Few Snow Showers / Wind' },
	4800: { iconFile: 'SctFl', textModifier: "Sct'd Flurries" },
	4809: { iconFile: 'NSctFl', textModifier: "Sct'd Flurries" },
	4810: { iconFile: 'Wnd', textModifier: "Sct'd Flurries / Wind" },
	4819: { iconFile: 'Wnd', textModifier: "Sct'd Flurries / Wind" },
	4900: { iconFile: 'RaSn', textModifier: 'Rain / Snow Showers' },
	4910: { iconFile: 'RaSn', textModifier: 'Rain / Snow Showers / Wind' },
	5000: { iconFile: 'WndSn', textModifier: 'Snow / Blowing Snow' },
	5100: { iconFile: 'SltFrzRa', textModifier: 'Freezing Rain / Sleet' },
	5101: { iconFile: 'SltFrzRa', textModifier: 'Light Frz Rain / Sleet' },
	5110: { iconFile: 'SltFrzRa', textModifier: 'Freezing Rain / Sleet / Wind' },
	5111: { iconFile: 'SltFrzRa', textModifier: 'Light Frz Rain / Sleet / Wind' },
	5200: { iconFile: 'SnSlt', textModifier: 'Snow / Sleet' },
	5210: { iconFile: 'SnSlt', textModifier: 'Snow / Sleet / Wind' },
	5300: { iconFile: 'RaFrzRa', textModifier: 'Rain / Frz Rain' },
	5301: { iconFile: 'RaFrzRa', textModifier: 'Light Rain / Frz Rain' },
	5302: { iconFile: 'RaFrzRa', textModifier: 'Heavy Rain / Frz Rain' },
	5310: { iconFile: 'RaFrzRa', textModifier: 'Rain / Frz Rain / Wind' },
	5311: { iconFile: 'RaFrzRa', textModifier: 'Light Rain / Frz Rain / Wind' },
	5312: { iconFile: 'RaFrzRa', textModifier: 'Heavy Rain / Frz Rain / Wind' },
	5351: { iconFile: 'RaFrzRa', textModifier: 'Light Rain / Frz Rain / Fog' },
	5400: { iconFile: 'HvySn', textModifier: 'Snow Squalls' },
	5409: { iconFile: 'HvySn', textModifier: 'Snow Squalls' },
	5500: { iconFile: 'SctSh', textModifier: 'Squalls' },
	5509: { iconFile: 'NSctSh', textModifier: 'Squalls' },
	5600: { iconFile: 'TsSn', textModifier: 'Thunder Snow' },
	5610: { iconFile: 'TsSn', textModifier: 'Thunder Snow / Wind' },
	5700: { iconFile: 'SctStrTs', textModifier: "Scattered Strong T'storms" },
	5709: { iconFile: 'NSctStrTs', textModifier: "Sct'd Strong T'storms" },
	5710: { iconFile: 'SctStrTs', textModifier: "Sct'd Strong T'storms / Wind" },
	5719: { iconFile: 'NSctStrTs', textModifier: "Sct'd Strong T'storms / Wind" },
	6000: { iconFile: 'Drz', textModifier: 'Drizzle Early' },
	6003: { iconFile: 'AMDrz', textModifier: 'AM Drizzle' },
	6010: { iconFile: 'Drz', textModifier: 'Drizzle / Wind Early' },
	6013: { iconFile: 'AMDrz', textModifier: 'AM Drizzle / Wind' },
	6100: { iconFile: 'LtRa', textModifier: 'Showers Early' },
	6103: { iconFile: 'AMSh', textModifier: 'AM Showers' },
	6110: { iconFile: 'LtRa', textModifier: 'Showers / Wind Early' },
	6113: { iconFile: 'AMSh', textModifier: 'AM Showers / Wind' },
	6140: { iconFile: 'LtRa', textModifier: "T'showers Early" },
	6143: { iconFile: 'AMSh', textModifier: "AM T'showers" },
	6170: { iconFile: 'LtRa', textModifier: "T'showers / Wind Early" },
	6173: { iconFile: 'AMSh', textModifier: "AM T'showers" },
	6200: { iconFile: 'Tss', textModifier: "T'storms Early" },
	6203: { iconFile: 'AMTs', textModifier: "AM T'storms" },
	6210: { iconFile: 'Tss', textModifier: "T'storms / Wind Early" },
	6213: { iconFile: 'AMTs', textModifier: "AM T'storms / Wind" },
	6300: { iconFile: 'Ra', textModifier: 'Rain Early' },
	6301: { iconFile: 'LtRa', textModifier: 'Light Rain Early' },
	6303: { iconFile: 'AMRa', textModifier: 'AM Rain' },
	6304: { iconFile: 'AMSh', textModifier: 'AM Light Rain' },
	6310: { iconFile: 'WndRa', textModifier: 'Rain / Wind Early' },
	6311: { iconFile: 'LtRa', textModifier: 'Light Rain / Wind Early' },
	6313: { iconFile: 'AMRa', textModifier: 'AM Rain / Wind' },
	6314: { iconFile: 'AMSh', textModifier: 'AM Light Rain / Wind' },
	6400: { iconFile: 'RaSn', textModifier: 'Rain / Snow Early' },
	6401: { iconFile: 'RaSn', textModifier: 'Rain / Snow Showers Early' },
	6403: { iconFile: 'AMRaSn', textModifier: 'AM Rain /Snow' },
	6404: { iconFile: 'AMRaSn', textModifier: 'AM Rain / Snow Showers' },
	6410: { iconFile: 'RaSn', textModifier: 'Rain / Snow / Wind Early' },
	6411: { iconFile: 'RaSn', textModifier: 'Rain / Snow Showers / Wind Early' },
	6413: { iconFile: 'AMRaSn', textModifier: 'AM Rain / Snow / Wind' },
	6414: { iconFile: 'AMRaSn', textModifier: 'AM Rain / Snow Showers' },
	6500: { iconFile: 'RaFrzRa', textModifier: 'Rain / Ice Early' },
	6501: { iconFile: 'RaFrzRa', textModifier: 'Light Rain / Ice Early' },
	6503: { iconFile: 'RaFrzRa', textModifier: 'AM Rain / Ice' },
	6504: { iconFile: 'RaFrzRa', textModifier: 'AM Light Rain / Ice' },
	6510: { iconFile: 'RaFrzRa', textModifier: 'Rain / Ice / Wind Early' },
	6511: { iconFile: 'RaFrzRa', textModifier: 'Light Rain / Ice / Wind Early' },
	6513: { iconFile: 'RaFrzRa', textModifier: 'AM Rain / Ice / Wind' },
	6514: { iconFile: 'RaFrzRa', textModifier: 'AM Light Rain / Ice / Wind' },
	6600: { iconFile: 'SltFrzRa', textModifier: 'Ice Early' },
	6603: { iconFile: 'SltFrzRa', textModifier: 'AM Ice' },
	6610: { iconFile: 'SltFrzRa', textModifier: 'Ice / Wind Early' },
	6613: { iconFile: 'SltFrzRa', textModifier: 'AM Ice / Wind' },
	6700: { iconFile: 'Mix', textModifier: 'Wintry Mix Early' },
	6701: { iconFile: 'LtMix', textModifier: 'Light Wintry Mix Early' },
	6703: { iconFile: 'AMMix', textModifier: 'AM Wintry Mix' },
	6704: { iconFile: 'AMMix', textModifier: 'AM Light Wintry Mix' },
	6710: { iconFile: 'Mix', textModifier: 'Wintry Mix / Wind Early' },
	6711: { iconFile: 'LtMix', textModifier: 'Light Wintry Mix / Wind Early' },
	6713: { iconFile: 'AMMix', textModifier: 'AM Wintry Mix / Wind' },
	6714: { iconFile: 'AMMix', textModifier: 'AM Light Wintry Mix / Wind' },
	6800: { iconFile: 'LtSn', textModifier: 'Snow Showers Early' },
	6803: { iconFile: 'AMSnSh', textModifier: 'AM Snow Showers' },
	6810: { iconFile: 'LtSn', textModifier: 'Snow Showers / Wind Early' },
	6813: { iconFile: 'AMSnSh', textModifier: 'AM Snow Showers / Wind' },
	6900: { iconFile: 'Sn', textModifier: 'Snow Early' },
	6901: { iconFile: 'LtSn', textModifier: 'Light Snow Early' },
	6903: { iconFile: 'AMSn', textModifier: 'AM Snow' },
	6904: { iconFile: 'AMSnSh', textModifier: 'AM Light Snow' },
	6910: { iconFile: 'WndSn', textModifier: 'Snow / Wind Early' },
	6911: { iconFile: 'LtSn', textModifier: 'Light Snow / Wind Early' },
	6913: { iconFile: 'AMSn', textModifier: 'AM Snow / Wind' },
	6914: { iconFile: 'AMSnSh', textModifier: 'AM Light Snow / Wind' },
	7000: { iconFile: 'Drz', textModifier: 'Drizzle Late' },
	7003: { iconFile: 'PMDrz', textModifier: 'PM Drizzle' },
	7010: { iconFile: 'Drz', textModifier: 'Drizzle / Wind Late' },
	7013: { iconFile: 'PMDrz', textModifier: 'PM Drizzle / Wind' },
	7100: { iconFile: 'LtRa', textModifier: 'Showers Late' },
	7103: { iconFile: 'PMSh', textModifier: 'PM Showers' },
	7110: { iconFile: 'LtRa', textModifier: 'Showers / Wind Late' },
	7113: { iconFile: 'PMSh', textModifier: 'PM Showers / Wind' },
	7140: { iconFile: 'LtRa', textModifier: "T'showers Late" },
	7143: { iconFile: 'PMSh', textModifier: "PM T'showers" },
	7170: { iconFile: 'LtRa', textModifier: "T'showers / Wind Late" },
	7173: { iconFile: 'PMSh', textModifier: "PM T'showers" },
	7200: { iconFile: 'Tss', textModifier: "T'storms Late" },
	7203: { iconFile: 'PMTs', textModifier: "PM T'storms" },
	7210: { iconFile: 'Tss', textModifier: "T'storms / Wind Late" },
	7213: { iconFile: 'PMTs', textModifier: "PM T'storms / Wind" },
	7300: { iconFile: 'Ra', textModifier: 'Rain Late' },
	7301: { iconFile: 'LtRa', textModifier: 'Light Rain Late' },
	7303: { iconFile: 'PMRa', textModifier: 'PM Rain' },
	7304: { iconFile: 'PMSh', textModifier: 'PM Light Rain' },
	7310: { iconFile: 'WndRa', textModifier: 'Rain / Wind Late' },
	7311: { iconFile: 'LtRa', textModifier: 'Light Rain / Wind Late' },
	7313: { iconFile: 'PMRa', textModifier: 'PM Rain / Wind' },
	7314: { iconFile: 'PMSh', textModifier: 'PM Light Rain / Wind' },
	7400: { iconFile: 'RaSn', textModifier: 'Rain / Snow Late' },
	7401: { iconFile: 'RaSn', textModifier: 'Rain / Snow Showers Late' },
	7403: { iconFile: 'PMRaSn', textModifier: 'PM Rain / Snow' },
	7404: { iconFile: 'PMRaSn', textModifier: 'PM Rain / Snow Showers' },
	7410: { iconFile: 'RaSn', textModifier: 'Rain / Snow / Wind Late' },
	7411: { iconFile: 'RaSn', textModifier: 'Rain / Snow Showers / Wind Late' },
	7413: { iconFile: 'PMRaSn', textModifier: 'PM Rain / Snow / Wind' },
	7414: { iconFile: 'PMRaSn', textModifier: 'PM Rain / Snow Showers' },
	7500: { iconFile: 'RaFrzRa', textModifier: 'Rain / Ice Late' },
	7501: { iconFile: 'RaFrzRa', textModifier: 'Light Rain / Ice Late' },
	7503: { iconFile: 'RaFrzRa', textModifier: 'PM Rain / Ice' },
	7504: { iconFile: 'RaFrzRa', textModifier: 'PM Light Rain / Ice' },
	7510: { iconFile: 'RaFrzRa', textModifier: 'Rain / Ice / Wind Late' },
	7511: { iconFile: 'RaFrzRa', textModifier: 'Light Rain / Ice / Wind Late' },
	7513: { iconFile: 'RaFrzRa', textModifier: 'PM Rain / Ice / Wind' },
	7514: { iconFile: 'RaFrzRa', textModifier: 'PM Light Rain / Ice / Wind' },
	7600: { iconFile: 'SltFrzRa', textModifier: 'Ice Late' },
	7603: { iconFile: 'SltFrzRa', textModifier: 'PM Ice' },
	7610: { iconFile: 'SltFrzRa', textModifier: 'Ice / Wind Late' },
	7613: { iconFile: 'SltFrzRa', textModifier: 'PM Ice / Wind' },
	7700: { iconFile: 'Mix', textModifier: 'Wintry Mix Late' },
	7701: { iconFile: 'LtMix', textModifier: 'Light Wintry Mix Late' },
	7703: { iconFile: 'PMMix', textModifier: 'PM Wintry Mix' },
	7704: { iconFile: 'PMMix', textModifier: 'PM Light Wintry Mix' },
	7710: { iconFile: 'Mix', textModifier: 'Wintry Mix / Wind Late' },
	7711: { iconFile: 'LtMix', textModifier: 'Light Wintry Mix / Wind Late' },
	7713: { iconFile: 'PMMix', textModifier: 'PM Wintry Mix / Wind' },
	7714: { iconFile: 'PMMix', textModifier: 'PM Light Wintry Mix / Wind' },
	7800: { iconFile: 'LtSn', textModifier: 'Snow Showers Late' },
	7803: { iconFile: 'PMSnSh', textModifier: 'PM Snow Showers' },
	7810: { iconFile: 'LtSn', textModifier: 'Snow Showers / Wind Late' },
	7813: { iconFile: 'PMSnSh', textModifier: 'PM Snow Showers / Wind' },
	7900: { iconFile: 'Sn', textModifier: 'Snow Late' },
	7901: { iconFile: 'LtSn', textModifier: 'Light Snow Late' },
	7903: { iconFile: 'PMSn', textModifier: 'PM Snow' },
	7904: { iconFile: 'PMSnSh', textModifier: 'PM Light Snow' },
	7910: { iconFile: 'WndSn', textModifier: 'Snow / Wind Late' },
	7911: { iconFile: 'LtSn', textModifier: 'Light Snow / Wind Late' },
	7913: { iconFile: 'PMSn', textModifier: 'PM Snow / Wind' },
	7914: { iconFile: 'PMSnSh', textModifier: 'PM Light Snow / Wind' },
	8000: { iconFile: 'RaToSn', textModifier: 'Rain to Snow' },
	8010: { iconFile: 'RaToSn', textModifier: 'Rain to Snow / Wind' },
	8100: { iconFile: 'RaFrzRa', textModifier: 'Rain to Ice' },
	8110: { iconFile: 'RaFrzRa', textModifier: 'Rain to Ice / Wind' },
	8200: { iconFile: 'SnToRa', textModifier: 'Snow to Rain' },
	8210: { iconFile: 'SnToRa', textModifier: 'Snow to Rain / Wind' },
	8300: { iconFile: 'Mix', textModifier: 'Snow and Ice to Rain' },
	8310: { iconFile: 'Mix', textModifier: 'Snow and Ice to Rain / Wind' },
	8400: { iconFile: 'SnFrzRa', textModifier: 'Snow to Ice' },
	8410: { iconFile: 'SnFrzRa', textModifier: 'Snow to Ice / Wind' },
	8500: { iconFile: 'RaFrzRa', textModifier: 'Ice to Rain' },
	8510: { iconFile: 'RaFrzRa', textModifier: 'Ice to Rain / Wind' },
	8600: { iconFile: 'SnFrzRa', textModifier: 'Ice to Snow' },
	8610: { iconFile: 'SnFrzRa', textModifier: 'Ice to Snow / Wind' },
	8700: { iconFile: 'Mix', textModifier: 'Wintry Mix to Snow' },
	8710: { iconFile: 'Mix', textModifier: 'Wintry Mix to Snow / Wind' },
	8800: { iconFile: 'Mix', textModifier: 'Snow to Wintry Mix' },
	8810: { iconFile: 'Mix', textModifier: 'Snow to Wintry Mix / Wind' },
	8900: { iconFile: 'Mix', textModifier: 'Wintry Mix to Rain' },
	8910: { iconFile: 'Mix', textModifier: 'Wintry Mix to Rain / Wind' },
	9000: { iconFile: 'NPc', textModifier: 'Clearing Late' },
	9003: { iconFile: 'CldPMSun', textModifier: 'AM Clouds / PM Sun' },
	9010: { iconFile: 'Wnd', textModifier: 'Clearing Late / Wind' },
	9013: { iconFile: 'PcWnd', textModifier: 'AM Clouds / PM Sun / Wind' },
	9100: { iconFile: 'Fog', textModifier: 'Fog Early / Clearing Late' },
	9103: { iconFile: 'AMFgPMSu', textModifier: 'AM Fog / PM Sun' },
	9110: { iconFile: 'Fog', textModifier: 'Fog Early / Clearing Late / Wind' },
	9113: { iconFile: 'AMFgPMSu', textModifier: 'AM Fog / PM Sun / Wind' },
	9200: { iconFile: 'AMFgPMCl', textModifier: 'Fog Early / Clouds Late' },
	9203: { iconFile: 'AMFgPMCl', textModifier: 'AM Fog / PM Clouds' },
	9210: { iconFile: 'AMFgPMCl', textModifier: 'Fog Early / Clouds Late / Wind' },
	9213: { iconFile: 'AMFgPMCl', textModifier: 'AM Fog / PM Clouds / Wind' },
	9300: { iconFile: 'Fog', textModifier: 'Fog Late' },
	9303: { iconFile: 'Fog', textModifier: 'PM Fog' },
	9310: { iconFile: 'Fog', textModifier: 'Fog / Wind Late' },
	9313: { iconFile: 'Fog', textModifier: 'PM Fog / Wind' },
	9500: { iconFile: 'Mix', textModifier: 'Rain to Wintry Mix' },
	9510: { iconFile: 'Mix', textModifier: 'Rain to Wintry Mix / Wind' },
}
var codetoCurrentVocals = {
	"BlowSn": "16_8_68_ICON",
	"Cld": "5_0_13_ICON",
	"CldWnd": "5_0_13_ICON",
	"DClrB12": "4_0_72_ICON",
	"DMc": "3_5_14_ICON",
	"DPc": "3_0_12_ICON",
	"Dust": "2_0_3_ICON",
	"Fog": "14_0_66_ICON",
	"Frigid": "9_0_43_ICON2",
	"Haze": "1_0_1_ICON",
	"HvyRa": "6_0_23_ICON",
	"HvySn": "9_8_44_ICON",
	"LtRa": "7_0_69_ICON",
	"LtSn": "9_0_48_ICON",
	"Mix": "12_0_67_ICON2",
	"NClr": "2_0_60_ICON",
	"NClrB12": "4_0_72_ICON",
	"NMc": "3_5_14_ICON",
	"NPc": "3_0_12_ICON",
	"NPcWnd": "3_0_12_ICON",
	"PcWnd": "3_0_12_ICON",
	"Ra": "6_0_17_ICON1",
	"RaSlt": "6_10_57_ICON",
	"RaSn": "6_8_56_ICON",
	"Slt": "10_0_54_ICON",
	"Smoke": "1_0_2_ICON",
	"Sn": "9_8_35_ICON",
	"SnFl": "9_0_41_ICON",
	"Sun": "1_0_11_ICON",
	"Thun": "5_13_61_ICON",
	"Ts": "6_13_71_ICON",
	"TsMix": "12_13_64_ICON",
	"TsSlt": "13_10_63_ICON",
	"TsSn": "9_13_62_ICON"
}

function getIcon(div, iconCode, type) {
	if (iconCode == 4400) {
		div.css({ "background-image": "url(images/newicons/blank.png)", "background-size": "100% 100%" })
	} else {
		if (type == "current") {
			div.css({ "background-image": "url(images/newicons/" + codeToCurrent[iconCode].iconFile + ".apng)", "background-size": "100% 100%" })
		} else if (type == "forecast") {
			div.css({ "background-image": "url(images/newicons/" + codetoFcst[iconCode].iconFile + ".apng)", "background-size": "100% 100%" })
		}

	}
}

function vocallocal(temp, cond) {
	var vlArr = ['narrations/vocallocal/default.mp3'];
	vlArr.push(`narrations/vocallocal/temps/${temp.toString().replaceAll("-", "M")}_TEMP.mp3`);
	vlArr.push(`narrations/vocallocal/curcond/${codetoCurrentVocals[codeToCurrent[cond].iconFile]}.mp3`);
	return vlArr;
}

var stationNameFilters = [
	//doing this because some of these piss me off
	["International", "Int'l"],
	["Hartsfield-Jackson ", ""],
]
function formatStationName(stationname) {
	var newstation = stationname;
	for (var i = 0; i < stationNameFilters.length; i++) {
		var ft = stationNameFilters[i];
		newstation = newstation.replaceAll(ft[0], ft[1]);
	}
	if (newstation.includes(" - ")) { newstation = newstation.split(" - ")[1]; }
	return newstation;
}